name: Build Debug

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set Version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionName: "${{ github.ref }}"

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
            
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./app/build/outputs/apk/debug/app-debug.apk
            asset_name: debug.apk
            asset_content_type: application/gzip
       
